before:
  hooks:
    - go mod tidy
builds:
  - id: anyisland
    main: ./cmd/anyisland
    binary: anyisland
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/nathfavour/anyisland/internal/cli.Version=v0.0.0-{{.ShortCommit}} -X github.com/nathfavour/anyisland/internal/cli.Commit={{.Commit}} -X github.com/nathfavour/anyisland/internal/cli.BuildTime={{.Date}}
  - id: anyisland-android
    main: ./cmd/anyisland
    binary: anyisland
    env:
      - CGO_ENABLED=0
    goos:
      - android
    goarch:
      - arm64
    ldflags:
      - -s -w -X github.com/nathfavour/anyisland/internal/cli.Version=v0.0.0-{{.ShortCommit}} -X github.com/nathfavour/anyisland/internal/cli.Commit={{.Commit}} -X github.com/nathfavour/anyisland/internal/cli.BuildTime={{.Date}}
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  mode: replace
